"""Add tenant fields to users table

Revision ID: 30c47d716cc4
Revises: fa5b1aceebaf
Create Date: 2025-07-12 15:58:02.105070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c47d716cc4'
down_revision: Union[str, None] = 'fa5b1aceebaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
