"""add_advanced_crm_tables

Revision ID: fef60ef31522
Revises: 30c47d716cc4
Create Date: 2025-07-15 14:44:24.150929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef60ef31522'
down_revision: Union[str, None] = '30c47d716cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.String(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('interaction_type', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_billable', sa.Boolean(), nullable=True),
    sa.Column('billable_hours', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.system_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.system_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_interactions_id'), 'customer_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_customer_interactions_interaction_type'), 'customer_interactions', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_customer_interactions_system_id'), 'customer_interactions', ['system_id'], unique=True)
    op.create_table('customer_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.String(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('note_type', sa.String(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.system_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.system_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_notes_id'), 'customer_notes', ['id'], unique=False)
    op.create_index(op.f('ix_customer_notes_system_id'), 'customer_notes', ['system_id'], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('qualification_status', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('estimated_value', sa.String(), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('expected_close_date', sa.DateTime(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('address_line1', sa.String(), nullable=True),
    sa.Column('address_line2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('converted_to_customer', sa.Boolean(), nullable=True),
    sa.Column('converted_customer_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_contacted', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.system_id'], ),
    sa.ForeignKeyConstraint(['converted_customer_id'], ['customers.system_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_name'), 'leads', ['name'], unique=False)
    op.create_index(op.f('ix_leads_system_id'), 'leads', ['system_id'], unique=True)
    op.create_table('lead_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.String(), nullable=True),
    sa.Column('lead_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('interaction_type', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.system_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.system_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_interactions_id'), 'lead_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_lead_interactions_interaction_type'), 'lead_interactions', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_lead_interactions_system_id'), 'lead_interactions', ['system_id'], unique=True)
    op.drop_index(op.f('idx_password_vault_access'), table_name='password_vault')
    op.drop_index(op.f('idx_password_vault_user'), table_name='password_vault')
    op.create_index(op.f('ix_password_vault_id'), 'password_vault', ['id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_password_vault_id'), table_name='password_vault')
    op.create_index(op.f('idx_password_vault_user'), 'password_vault', ['user_system_id'], unique=False)
    op.create_index(op.f('idx_password_vault_access'), 'password_vault', ['vault_access_code'], unique=False)
    op.drop_index(op.f('ix_lead_interactions_system_id'), table_name='lead_interactions')
    op.drop_index(op.f('ix_lead_interactions_interaction_type'), table_name='lead_interactions')
    op.drop_index(op.f('ix_lead_interactions_id'), table_name='lead_interactions')
    op.drop_table('lead_interactions')
    op.drop_index(op.f('ix_leads_system_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_customer_notes_system_id'), table_name='customer_notes')
    op.drop_index(op.f('ix_customer_notes_id'), table_name='customer_notes')
    op.drop_table('customer_notes')
    op.drop_index(op.f('ix_customer_interactions_system_id'), table_name='customer_interactions')
    op.drop_index(op.f('ix_customer_interactions_interaction_type'), table_name='customer_interactions')
    op.drop_index(op.f('ix_customer_interactions_id'), table_name='customer_interactions')
    op.drop_table('customer_interactions')
    # ### end Alembic commands ###
